version: "3"
services:
    php:
        external_links:
        - mysql_db_1:db
        networks:
        - default
        - mysql_default
        volumes:
        - symfony-docker-vendor-sync:/opt/vendor:nocopy
        - symfony-docker-src-sync:/opt/src:nocopy
        - symfony-docker-bin-sync:/opt/bin:nocopy
        - symfony-docker-web-sync:/opt/web:nocopy
        - symfony-docker-app-sync:/opt/app:nocopy
        - symfony-docker-var-sync:/opt/var:nocopy
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.56.1"
            PHP_IDE_CONFIG: "serverName=docker"
    nginx:
        external_links:
        - nginx-proxy_nginx-proxy_1:nginx-proxy
        links:
        - php
        depends_on:
        - php
        networks:
        - default
        - nginx-proxy_default
        expose:
        - 80
        volumes:
        - symfony-docker-vendor-sync:/opt/vendor:nocopy
        - symfony-docker-src-sync:/opt/src:nocopy
        - symfony-docker-bin-sync:/opt/bin:nocopy
        - symfony-docker-web-sync:/opt/web:nocopy
        - symfony-docker-app-sync:/opt/app:nocopy
        - symfony-docker-var-sync:/opt/var:nocopy
networks:
    mysql_default:
        external: true
    nginx-proxy_default:
        external: true
volumes:
    symfony-docker-vendor-sync:
        external: true
    symfony-docker-src-sync:
        external: true
    symfony-docker-bin-sync:
        external: true
    symfony-docker-web-sync:
        external: true
    symfony-docker-app-sync:
        external: true
    symfony-docker-var-sync:
        external: true
    mysql-data:
        external: true
